### ISSUE TITLE
Policy.Utils.ps1 should not use PSChildResource as parameter type

### ISSUE THREAD

**Issue by fawohlsc** [fawohlsc/azure-policy-testing#26]
In Azure PowerShell, not all resources inherit from PSChildResource (class inheritance).
So Get-ComplianceState cannot cast this resources like PSNamespaceAttributes to PSChildResource.
Change to different object parameter like PSObject.

**Comment by aschabus** [comment]
I think the best would be to change it to string as we only need the id resource to filter for the resource.
And we can get the id directly from e.g. a put request without the need of recreating an object.

**Comment by fawohlsc** [comment]
Fixed, so closing.
