### ISSUE TITLE
Organize tests around Policies, not Centralized

### ISSUE THREAD

**Issue by NickFadz** [fawohlsc/azure-policy-testing#3]
As currently designed, all testing would consolidate around the single script, Policy.Tests.ps1. This makes testing an individual policy difficult. Please consider organizing tests around individual policies.

This has the side benefit of allowing CI/CD whenever there's a Add/Update to Policies automatically.

**Comment by fawohlsc** [comment]
@NickFadz as discussed makes total sense to split the tests per policy to also allow easy scaling towards a more complex hierarchy of management groups as described [here](https://github.com/fawohlsc/azure-policy-testing#can-we-scale-this-testing-approach-towards-a-complex-management-group-hierarchy). Will gather some more feedback, prioritize the issues and implement the changes. Will let you know once completed. Many thanks upfront for your superb feedback 🥇
