### ISSUE TITLE
Azure Pipelines Port

### ISSUE THREAD

**Issue by keyoke** [fawohlsc/azure-policy-testing#9]
**Is your feature request related to a problem? Please describe.**
Many organizations still leverage Azure DevOps i.e. Pipelines and would have needs to perform testing of policies

**Describe the solution you'd like**
Initial v1 port of existing GitHub workflow to Azure Pipelines.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

Already started working on a simple port, if this is something you are interested in, I can contribute back - https://github.com/keyoke/azure-policy-testing/blob/az-pipelines-port/azure-pipelines.yaml

**Comment by fawohlsc** [comment]
@keyoke Please port back. It's an awesome enhancement. Many thanks for your contributions mate!

**Comment by fawohlsc** [comment]
Port completed. Closing issue.
